# Generated by Django 6.0.3 on 2026-03-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isp_number', models.CharField(max_length=20, unique=True)),
                ('buyer_initials', models.CharField(max_length=10)),
                ('seller_first_name', models.CharField(max_length=100)),
                ('seller_last_name', models.CharField(max_length=100)),
                ('seller_address', models.CharField(max_length=255)),
                ('seller_city', models.CharField(max_length=100)),
                ('seller_state', models.CharField(max_length=50)),
                ('seller_zip', models.CharField(max_length=20)),
                ('seller_phone', models.CharField(max_length=20)),
                ('seller_email', models.EmailField(max_length=254)),
                ('drivers_license_state', models.CharField(max_length=50)),
                ('drivers_license_number', models.CharField(max_length=50)),
                ('purchase_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocation_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allocation_difference', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reconciliation_status', models.CharField(default='under', max_length=20)),
                ('workflow_status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
