# Generated by Django 6.0.3 on 2026-04-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='check_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='gift_card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_split_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(default='cash', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_other_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
