# Generated by Django 6.0.3 on 2026-04-02 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchase_check_number_purchase_gift_card_last4_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='export_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='exported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exported_purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
