# Generated by Django 6.0.3 on 2026-04-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_buyerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='location',
            field=models.CharField(default='Select Your Location', max_length=20),
            preserve_default=False,
        ),
    ]
