# Generated by Django 6.0.3 on 2026-04-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_purchase_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='second_check_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='second_gift_card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='purchase',
            name='second_payment_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='second_payment_other_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
