# Generated by Django 6.0.3 on 2026-04-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_purchase_second_check_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='primary_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='second_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
