# Generated by Django 6.0.3 on 2026-04-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_purchase_primary_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='can_edit_all_purchases',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='can_reopen_purchases',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
    ]
