# Generated by Django 6.0.3 on 2026-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_purchaseeditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='export_batch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
