# Generated by Django 6.0.3 on 2026-04-17 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_purchase_export_batch_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='export_batch_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='export_batch_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['workflow_status'], name='purchases_p_workflo_4cda9f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['reconciliation_status'], name='purchases_p_reconci_06ab0b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['created_at'], name='purchases_p_created_315d57_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['finalized_at'], name='purchases_p_finaliz_3b337a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['exported_at'], name='purchases_p_exporte_0700ac_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['buyer_initials'], name='purchases_p_buyer_i_c6df38_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['location'], name='purchases_p_locatio_0b2de1_idx'),
        ),
    ]
