# Generated by Django 6.0.3 on 2026-04-24 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_remove_purchase_export_batch_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyerprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='reconciliation_status',
            field=models.CharField(choices=[('under', 'Under'), ('balanced', 'Balanced'), ('over', 'Over')], default='under', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20),
        ),
    ]
