# Generated by Django 6.0.3 on 2026-04-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0014_alter_purchase_options_alter_purchaseitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
