# Generated by Django 6.0.3 on 2026-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0015_buyerprofile_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='password_last_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
